# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'load_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoadWindow(object):
    def setupUi(self, LoadWindow):
        LoadWindow.setObjectName("LoadWindow")
        LoadWindow.resize(545, 346)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Icons/app_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LoadWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(LoadWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(0, -10, 551, 361))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("../../../Icons/logo.png"))
        self.logo.setObjectName("logo")
        LoadWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoadWindow)
        QtCore.QMetaObject.connectSlotsByName(LoadWindow)

    def retranslateUi(self, LoadWindow):
        _translate = QtCore.QCoreApplication.translate
        LoadWindow.setWindowTitle(_translate("LoadWindow", "Cash Counter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoadWindow = QtWidgets.QMainWindow()
    ui = Ui_LoadWindow()
    ui.setupUi(LoadWindow)
    LoadWindow.show()
    sys.exit(app.exec_())
